name: "clickable"
description: "Build arm64 applications for Ubuntu Touch"
inputs:
  image:
    description: 'Image'
    required: true
  workspace:
    description: 'workspace mount'
    default: ${{ github.event.repository.name }}
    required: false
  shell:
    description: 'Use a specific shell'
    required: false
    default: bash
  run:
    description: 'Run command in container'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
